from near_recommender.src.recommender import get_recommendations_per_user
from near_recommender.src.models.friends_friends import get_friends_of_friends
from near_recommender.src.models.similar_posts import get_similar_post_users, update_corpus
from near_recommender.src.models.similar_tags import get_similar_tags_users
from near_recommender.src.models.trending_users import get_trending_users
